title: Yiming Ma # your name (or website title) here
logo: "/images/newlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research Data Analyst at Institute for Health - Rutgers University
  <br><br>  
  Penn Alumni -  Social Policy + Data Analytics Program
  <br><br>
  <a href="https://www.linkedin.com/in/yimingma11/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
